export const privacyContent = `# Privacy Policy

*Effective Date: 5th May 2025*

## 1. Data We Collect
- **Account Data:** Email, username, and authentication details.
- **Usage Data:** Images generated by the app.
- **User Input:** Customisation of the images.

## 2. How We Use Your Data
- To provide and improve Petraits.
- To personalize your experience.
- To analyze and enhance AI responses.
- To manage account authentication.

## 3. Data Storage and Security
Your user data is securely stored on our servers. We implement security measures to protect your data.

## 4. Data Sharing
We do **not** sell your personal data. We may share data with third-party services for analytics, authentication, and payment processing.

## 5. Account Deletion
You may request to delete your account, and we will remove your personal data in accordance with applicable laws.

## 6. Governing Law
This Privacy Policy is governed by the laws of **Australia**.`;
